### ISSUE TITLE
[Lake][ETL] ETL.md - Explain architecture & ux end-to-end

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/pdr-backend#1002]
### Background / motivation

To integrate duckDB (#685)[https://github.com/oceanprotocol/pdr-backend/issues/685] the user should be able to follow the README.md, get their lake setup, and complete all the work end-to-end without any issues.

Further, if the user should experience any issues, they should be able to resolve/heal the process effortlessly.

### DoD
Write README.md for updated lake, and verify that it's working end-to-end

Tasks:
- [x] Write new lake README.md
- [x] Test README.md end-to-end
- [x] Documentation is working as expected

**Comment by KatunaNorbert** [comment]
Reviewed the README and have some feedback:
- [ ] Add information about where the data comes from and what kind of data we are ingesting into the lake
- [ ] I suggest to move the 'use analytics' part into a different README, keeping the `lake-and-etl` strictly about describing and using the lake + etl
- [ ] There is no information about the data available, tables etc. I would expect to visually see the data that I'm going to get before going trough the lake setup process
- [ ] Add a simple example containing the command the users has to execute to go trough the etl end to end
- [ ] The README is long and we don't have any legend on the top to make it easy to see the content and navigate trough different sections. Add a legend on the top of the page, example:
<img width="1150" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTN1QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7b546130172b86fcea430b80da93bb9f428249b6/Screenshot%202024-05-17%20at%2012.40.51.png" alt="Screenshot 2024-05-17 at 12.40.51.png" />

**Comment by idiom-bytes** [comment]
Readme has been concluded in PR for issue #1001 -> https://github.com/oceanprotocol/pdr-backend/pull/1100
