### ISSUE TITLE
[Sim plots] Too many plots at once; fix via >1 page selectable via sidebar 

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#1021]
### TODOs

-  [ ] Refactor the sim plots webapp, via a tab on left for each group of plots. (See "inspiration" below)

Specifics: using the same style as "inspiration" below, group the plots with the following Sidebar label -> plots:
- "Profit" :: {Predictoor profit vs time, Trader profit vs time, pdr profit dist, trader profit dist}
- "Model performance" -> {accuracy, f1, log loss}
- "Model response" -> {Variable importances, Contours = model response}

### Background / motivation

From matplotlib -> streamlit work [#749](https://github.com/oceanprotocol/pdr-backend/issues/749) then streamlit -> dash work [#906](https://github.com/oceanprotocol/pdr-backend/issues/906) we now have beautiful sim plots in a webapp, great. See "status quo screenshot" below.

However there's already a _lot_ of plots in one webapp. They could readily be grouped, each into their own screen, giving them more "space to breathe" with more interactivity etc. For example, impacts + sweeps could go into their own screen.

### Towards a solution

What we want is a Plotly/Dash "Multi-Page App", where:
- there's a sidebar on the left. Click a button on the sidebar and it will show you some of the plots. (Ideally each button has an icon next to it.) See "Inspiration" below.
- it's all still the "sim plots" app

### Resources

- `dash.plotly.com` "Multi-Page Apps and URL Support" [docs](https://dash.plotly.com/urls), [video tutorial](https://www.youtube.com/watch?v=pJMZ0r84Rqs)
- "dash-multi-page-app-demos", by AnnMarieW, [github README](https://github.com/AnnMarieW/dash-multi-page-app-demos), with curated links to many more tutorials
- "How to Create a Multipage Dash App", by Michael McManus [blog](https://medium.com/@mcmanus_data_works/how-to-create-a-multipage-dash-app-261a8699ac3f)
- "Multipage Python Dash App" by Charming Data, [video part 1](https://www.youtube.com/watch?v=Hc9_-ncr4nU), [video part 2](https://youtu.be/MtSgh6FOL7I?si=DAxOttll9NnYxm4l). Part 2 at 0:38 shows a left sidebar; the video shows how

### Inspiration

![Screenshot 2024-05-11 at 09 03 02 2](https://github.com/oceanprotocol/pdr-backend/assets/5305452/8ee9a386-81c0-48f1-80d5-930dba36ea78)

### Status quo screenshot

![FireShot Capture 017 - Dash - 127 0 0 1](https://github.com/oceanprotocol/pdr-backend/assets/5305452/d698d38a-ec31-4e08-b210-4dc9a8ef2cda)

**Comment by KatunaNorbert** [comment]
Do we really need multiple pages for this?
I suggest using tabs, this will allow to keep common components such as: SimulationID, State visible on the top and only change the displayed plots.

**Comment by trentmc** [comment]
> I suggest using tabs, this will allow to keep common components such as: SimulationID, State visible on the top and only change the displayed plots.

I agree.

> Do we really need multiple pages for this?

"Multiple pages" has two meanings:
1. the general idea of an app that has >1 pages, versus different tabs
2. a Plotly/Dash "Multi-Page App", which is how you implement >1 pages OR different tabs

We are in category (2). We want to implement different tabs, but how you do it with Plotly/Dash is via a "Multi-Page App". (At least that's my understanding of it! If you see a simpler way, go for it.)

**Comment by KatunaNorbert** [comment]
This is what I mean:
https://dash.plotly.com/dash-core-components/tab

**Comment by trentmc** [comment]
> This is what I mean: https://dash.plotly.com/dash-core-components/tab

Thank you for finding that. I think I'd been confused, it had looked like tabs had been deprecated, but digging around right now, it looks like they're still properly supported.

Therefore: yes do go with the "tab" core component.

**Comment by KatunaNorbert** [comment]
Ok
