### ISSUE TITLE
[Lake][DuckDB] Bronze_pdr_predictions table is not updating

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/pdr-backend#1052]
After bronze tables are create, then new raw values are fetched, these new raw prediction values are not present inside the `bronze_predictions` table.

At first etl update run when bronze tables do not exist the flow it's working as expected.
On all the other runs the flow it's broken and only the bronze_pdr_slots table is updated.

Inspected the issue and this should be the reason:
- because we are using the same start date for all the bronze tables it looks at all the last timestamp across existing bronze tables and pics up the MAX or the highest value. Usually the timestamps on the slots table is grater then the ones from the predictions table and due to this there is going to be missing values in bronze_predictions_table, or no new values at all

Example:
After the first run this are the highest timestamp values for the bronze tables:
<img width="313" alt="Screenshot 2024-05-16 at 12 28 38" src="https://github.com/oceanprotocol/pdr-backend/assets/37236152/d921e165-801b-40c1-b7af-cc5e97a29323">

This is the last timestamp of the new data inside pdr_predictions:
<img width="453" alt="Screenshot 2024-05-16 at 12 30 57" src="https://github.com/oceanprotocol/pdr-backend/assets/37236152/8e5f2988-9110-4a99-9d6c-11889fab89d0">

And this is the start and final timestamp values for filtering new data for the bronze tables:
<img width="991" alt="Screenshot 2024-05-16 at 12 34 01" src="https://github.com/oceanprotocol/pdr-backend/assets/37236152/460d49c1-5273-40d3-b200-dedc299b420a">

You can see that there is no new prediction data between the filter bounds of the bronze tables, so bronze_pdr_predictions is not getting updated

**Comment by KatunaNorbert** [comment]
Tried using `last_event_timestamp` instead of `timestamp` for the start time calculation but not working

**Comment by KatunaNorbert** [comment]
Screenshots not working on Github, please check Zenhub

**Comment by idiom-bytes** [comment]
There were issues with local time that were causing problems.
Secondly, we should disable slots table and again, only look at bronze_predictions for now.

Addressed in latest version of duckdb-pr.

Closing issue.
