### ISSUE TITLE
[Lake]Fix the accuracy module for the ETL release

### ISSUE THREAD

**Issue by kdetry** [oceanprotocol/pdr-backend#1102]
Fix the accuracy module with the "fetch data logic" and make it ready for the release

**Comment by idiom-bytes** [comment]
The goal was not to modify the existing lake code... but to simply have an implementation of the old code working on this branch.

I spoke wtih @trentmc, we're going to merge the duckdb PR piece-by-piece.
https://github.com/oceanprotocol/pdr-backend/pull/1103

I'll be closing this ticket.
