### ISSUE TITLE
[Lake][DuckDB] Clean ppss handling, such that it's not so verbose

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/pdr-backend#1108]
### Background / motivation

In lake, ppss is being passed around like crazy although it's a configuration file...
https://github.com/oceanprotocol/pdr-backend/pull/1098

isn't there a better way to do all of this?

Approach A: Singleton
Approach B: Decorator
Approach C: Some other pattern...

### TODOs / DoD

Tasks:
- [ ] Clean up ppss as a pattern, such that it's accessed when needed, and doesn't have to be passed around so much

### Related github issues
https://github.com/oceanprotocol/pdr-backend/pull/1098

**Comment by trentmc** [comment]
> TODO: Clean up ppss as a pattern, such that it's accessed when needed, and doesn't have to be passed around so much

There's a better way to solve this:
- recall that ppss holds lake_ss. Which is a smaller amount of config, and exactly what lake should need
- so the solution is simply: **in lake code, pass around lake_ss (vs ppss)**. That's it. 

Definitely do not "clean up ppss", that's way too broad a scope

**Comment by calina-c** [comment]
> > TODO: Clean up ppss as a pattern, such that it's accessed when needed, and doesn't have to be passed around so much
> 
> There's a better way to solve this:
> 
> * recall that ppss holds lake_ss. Which is a smaller amount of config, and exactly what lake should need
> * so the solution is simply: **in lake code, pass around lake_ss (vs ppss)**. That's it.
> 
> Definitely do not "clean up ppss", that's way too broad a scope

That's exactly what we are doing now. We are passing around ppss.

This issue's goal was to remove that "passing around" part. The solution I proposed is for some objects to be "smart" about retrieving the ppss from their caller parent. If that looks too... "automagical", then we can close this issue and keep ppss handling like it is, i.e. passing it as a parameter.

**Comment by idiom-bytes** [comment]
ppss/lake_ss is nearly a configuration of the running environment
this should not need to be passed around

perhaps we can wrap it in a fixture or something such that we can access it anywhere, like within a namespace or something, without needing to do all of this

it's wild

**Comment by kdetry** [comment]
I suggest using a 'tagged' Multiton pattern for this issue. we can have multiple unique instances of the PPSS configuration, each identified by a specific tag. with this usage, PPSS can manage its own instances.

Here is an example for explaining what I mean with the "tagged" Multiton pattern

```python

class PPSS:
    _instances = {}

    def __new__(cls, tag=None, *args, **kwargs):
        if tag is None:
            # Create a new instance without caching
            instance = super(PPSS, cls).__new__(cls)
            instance._initialized = False
            return instance

        if tag not in cls._instances:
            cls._instances[tag] = super(PPSS, cls).__new__(cls)
            cls._instances[tag]._initialized = False
        return cls._instances[tag]

    def __init__(
        self,
        yaml_filename: Optional[str] = None,
        yaml_str: Optional[str] = None,
        network: Optional[str] = None,
        nested_override_args: Optional[dict] = None,
        d: Optional[dict] = None,
        tag: Optional[str] = None
    ):
        if self._initialized:
            return
        self._initialized = True
        # other existing codes...

          
# Example usage
# Create and cache an instance with tag 'config-lake'
ppss1 = PPSS('config-lake', yaml_filename='path/to/config1.yaml')

# Retrieve the cached instance with tag 'config1'
ppss1_cached = PPSS('config-lake')

# Create a new instance without caching
ppss_temp = PPSS(yaml_filename='path/to/temp/config.yaml')

```

This way ensures that when a tag is not provided, a new instance is created without using the cached instances.
If a tag is provided, the instance is cached and reused for that tag.

**Comment by kdetry** [comment]
Or, just an alternative, we can create a PPSSFactory that manages instances and returns according to their tags

**Comment by calina-c** [comment]
I had a call with Trent regarding this issue. We decided that the status quo is the most simple and not that bothersome and cluttered. It's a poor investment of our time to come up with creative solutions right now, so this issue should be closed, at least for now.
