### ISSUE TITLE
Running predictoor fails due to package version issue

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/pdr-backend#1132]
I got the latest version of pdr-backend, installed latest packages and run into the following error when running the predictoor bot with `pdr predictoor ..`:
`ImportError: cannot import name '_get_column_indices' from 'sklearn.utils'`

I inspected the issue and got it running again by downgrading the `scikit-learn` version from `1.5.0` to `1.4.0` as suggested in the following [conversation](https://stackoverflow.com/questions/78524575/importerror-cannot-import-name-get-column-indices-from-sklearn-utils)

Lowering the version might not be the best approach, and might have some impact on the current performance, so we might need to do some modification for pdr-backend to support the `1.5.0` version without breaking

**Comment by calina-c** [comment]
Did you nuke your venv? I had the same issue and as the tests are passing, I assumed that's the solution. It worked for me.

**Comment by KatunaNorbert** [comment]
I did not then, but I tried now nuking the venv and it's working, so I think we could close this issue if there are no more comments
