### ISSUE TITLE
[Sim] DuckDB tests failing inside github actions

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/pdr-backend#1303]
When using DuckDB queries for testing that the data required for getting the predictions is present, querying the database works on local environments but it fails when it runs inside the github actions tests

**Comment by idiom-bytes** [comment]
i think you have something wrong in your PR

all ETL tests are using DuckDB and they are working on both local and github action environments

**Comment by calina-c** [comment]
Encountered this multiple times with unrelated PRs and even dependency PRs. It used to be rare and intermittent, fixable by rerunning the tests. However, it seems to fail almost all the time now.

E.g. here for the second run https://github.com/oceanprotocol/pdr-backend/actions/runs/9692096671/job/26746113547?pr=1308

**Comment by KatunaNorbert** [comment]
There are some issues rn with subgraph, and because multiple ETL and Gql tests are based on subgraph requests when subgraph is down the tests fail.

@idiom-bytes is right, the DuckDB test are looking stable in other places, so let's focus on the specific issue here

**Comment by kdetry** [comment]
Can we close this issue ? @KatunaNorbert

**Comment by KatunaNorbert** [comment]
Yes, fixed inside #1313 by mocking GQLDataFactory step
