### ISSUE TITLE
[analytics, predictoor_v0.1] Create basic dashboard for Predictoors

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/pdr-backend#1325]
**Target**
Create a simple analytics dashboard for predictoors using the chain data from the lake
Super epic issue can be found [here](https://github.com/oceanprotocol/pdr-backend/issues/1328)
UI should follow the layout from [here](https://docs.google.com/presentation/d/18y_nfpc3e-dop5NtfIisgUkc-oPt8dft9WyAnqhSqZg/edit#slide=id.g20f5357f625_0_1639)

To do:
- [x] Create basic empty dash app that could be started from command line and opens a browser window
- [x] Display all the feeds and predictoor addresses, enable selection, and store them in state
- [x] Display following charts for a given list of feeds and predictoor addresses:

- Profit ( staked amount - payout amount)
- Accuracy ( how accuracy evolved over the time, similar to what we have in simulations )
- Costs( staked amount )

- [x] Write tests for used functions and dash elements
- [x] Update readme

As source data for charts use `payouts table`

**Comment by calina-c** [comment]
I'm wondering if all these dashboards should be merged at some point. I am counting:
- the sim plots dashboard
- the arima dashboard
- the lake description dashboard
- now the predictoor dashboard would be the 4th.

Is there no logical overlap that warrants unification. between some of these?

**Comment by KatunaNorbert** [comment]
> Is there no logical overlap that warrants unification. between some of these?

I don't see much overlapping between this, maybe something between predictoor dashboard and sim dashboard

**Comment by KatunaNorbert** [comment]
The scope of this issue is to create the most basic dashboard for Predictoors, while trying to encapsulate the most valuable data from the lake and the goal has been reached:
<img width="1428" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlN0QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--42b93bbe46c33d3d0466cc59c5c5a206ca94c8f7/Screenshot%202024-07-03%20at%2010.01.29.png" alt="Screenshot 2024-07-03 at 10.01.29.png" />

As you probably think looking at the UI there are multiple updates we can do to make the data easier to read and search, but we will handle all of that in the next version

For the scope of shipping the v0.1 let's just handle the minimal enhancements without updating the layout and components. A few a can think of are:
- [ ] Plots legend updates: the same legend is shown for each plot, we only show it once and win some space. Also to make it easier to follow, instead of feed address display the feed pair + timeframe, so legend will be `0x012 - BTC/USDT-5m`
- [ ] Make tables searchable. It's hard for now to find a specific predictoor address so we could have a quick win by making table searchable if the component allows us
- [ ] Handle no data found in lake. When no data is found in lake or there is an issue with ppss the app should display a message describing the issue and not break
