### ISSUE TITLE
[BMs] Make it easy to reproduce multisim benchmarking plots

### ISSUE THREAD

**Issue by graceful-coder** [oceanprotocol/pdr-backend#1332]
### Background / motivation

Plots improve the understanding of ML model benchmarks for Predictoor. Alternative tools like Codepen.io are difficult to integrate into pdr-backend, while Plotly is an easy addition to pdr-backend with the option to plot live multisim data.

### TODOs

- [ ] Implement Python Plotly to generate plots for benchmarks of different ML models.

**Comment by trentmc** [comment]
done
