### ISSUE TITLE
[Model/trade] Handling missing ohlcv data

### ISSUE THREAD

**Issue by UditGupta10** [oceanprotocol/pdr-backend#1386]
**Description**
When fetching data via api from an exchange such as Binance, I had observed gaps in the timestamps which are different from the requested interval.
For example: When fetching data from Binance for BTC/USDT pair at 5m interval for the past 5 years, there were 21 instances when the difference in successive timestamps deviated from the requested interval. In one case the difference was as high as 10 hours.

**Possible Solution**
- Check for missing data by checking the difference between successive timestamps.
- Impute new rows such that the difference between successive timestamps aligns with the requested interval.
- The simplest way to impute is to repeat the ohlcv values from the previous datapoint. Timestamps can be added to adhere to the interval requested.

**Context**
Checking and filling missing data is important as it might affect the model building and inferencing stage.

**Comment by trentmc** [comment]
This was done previously, several months ago

Udit will double-check, and re-open if needed
