### ISSUE TITLE
[PdrDashboard, v0.2] Allow user predictoor addresses configuration

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/pdr-backend#1402]
**Target**
Allow user to configure default predictoor addresses and easily see data based on that

**To do**
- [x] allow user to specify own predictoor addresses by a new "my_addresses" section inside "predictoor_ss" of **ppss.yaml** file
- [x] when dashboard is started and "my_addresses" are set, make the predictoor addresses inside the table and all the corresponding feeds selected( this will calculate and show the data for predictoors )
- [x] add a button called "My Predictoors" which resets the tables selected values to the predictoors from ppss.yaml, just like when the app is first started

**Comment by calina-c** [comment]
@KatunaNorbert I realised I initially marked #1403 as "work on" because it was before you merged the feed switch. Combined, I think the functionality now works as expected and we can close this issue. Can you confirm?

**Comment by KatunaNorbert** [comment]
Yes, we can close it
