### ISSUE TITLE
[Admin] Have a template to creating a new issue

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#1407]
### Background / motivation

Until recently, every time someone created a new issue in pdr-backend, it would follow a template something like what's in the "Reference template" below. It created good rails on issue creation. I (Trent) probably created 3/4 of the issues in pdr-backend and I loved to use it.

When the new template for PRs was brought in, the issue-creating template somehow got deprecated. 

Let's bring it back.

### TODOs

- [x] Update the pdr-backend repo such that when a new issue is created, it follows the "Reference template" below

### Appendix: Reference template

Title: `[Component name] Problem to solve, maybe how`

Body:
```text
### Background / motivation

(Optional) link to epic: [#xyz](https://github.com/oceanprotocol/pdr-backend/issues/xyz)

<Write background / motivation>

### TODOs

- [ ] <item 1>
- [ ] <item 2>

### Appendix: foo

Bar
```

**Comment by trentmc** [comment]
@KatunaNorbert @calina-c I mentioned this in sprint planning yesterday. If one of you has an in-between 30 min where you want to take this on, please do. Thank you!

**Comment by KatunaNorbert** [comment]
I can do it today

**Comment by KatunaNorbert** [comment]
Tested it and it doesn't seem to be working. Tried to create a new issue but the content didn't change...

**Comment by KatunaNorbert** [comment]
Hm.. I see, so if I go to Issues/new issue/edit templates it redirects me to `oceanprotocol/.github` which makes me to believe that the templates are constant trough all projects under the oceanprotocol organization. Probably I a modify the templates there will work, but I'm afraid that it will change it to the other projects as well. I'll inspect more to see If I can find something
