### ISSUE TITLE
Separate engine systems and components from webapp components

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/pdr-backend#1419]
**Is your feature request related to a problem? Please describe.**
Core tooling and CLI functionality is being restructured to serve FE requirements rather than remaining system-level functionality/API/interface
https://github.com/oceanprotocol/pdr-backend/pull/1319#issuecomment-2237411592

**Describe the solution you'd like**
1. Separate core engine systems and code from webapp functionality
`/pdr_backend/` -> serves all the core engine systems, apis, etc..
`/pdr_frontend/` -> provides all implementations for all webapp requirements

all core functionality for the web apps should then be referenced from pdr_backend

2. pytest should first run all coverage inside `pdr_backend/` and then `pdr_frontend/`

3. move the lake cli commands and functionality back to the lake_module. If a lake FE app wants to be built, it should call this functionality not move it over to it's own repo.

**Describe alternatives you've considered**
The current project architecture does not enforce SLAs with engine-level code, and provides the illusion that this functionality can/should be moved to the webapp/frontend.

**Additional context**
This doesn't help draw a clear line in the sand between engine-level functionality and FE-level functionality

**Comment by trentmc** [comment]
This issue is invalid. Please do NOT do it.

Details : See https://github.com/oceanprotocol/pdr-backend/pull/1319#issuecomment-2237492269

**Comment by idiom-bytes** [comment]
ok, I will re-write this issue to specifically address the lake validation/info logic that was moved outside of the core lake module
