### ISSUE TITLE
[trader] Save previous traded epoch

### ISSUE THREAD

**Issue by trizin** [oceanprotocol/pdr-backend#147]
### Background / motivation
Trader agent retains a record of the most recent traded epoch, but this record is cleared when the agent is shut down. Consequently, if a user initiates a trade, shuts the app, and then reruns it, the app might execute a duplicate trade for that same epoch.

### TODO:
- [x] Save previous traded epoch into a file.
- [x] Read from the file at startup to get the previous epochs for available feeds and do not trade for the same epoch.

**Comment by trentmc** [comment]
FYI, "last" should only be used where it's the last thing, ever. "Previous" is the word you were looking for. I changed accordingly.

FWIW most people make this mistake, even native English speakers. But it's worth using "previous" because it's more clear. (And less doom-sounding lol)

**Comment by trentmc** [comment]
> Trader agent retains a record of the most recent traded epoch, but this record is cleared when the agent is shut down. Consequently, if a user initiates a trade, shuts the app, and then reruns it, the app might execute a duplicate trade for that same epoch.

Put this in the description, please.

I like to use a format like the following. Perhaps you can use it too?
```
### Background / motivation

(content)

### TODOs

- [ ] Item 1
- [ ] Item 2
```
