### ISSUE TITLE
[BUG] CI on test_trueval_agent_batch.py gets stuck in infinite loop

### ISSUE THREAD

**Issue by trizin** [oceanprotocol/pdr-backend#229]
https://github.com/oceanprotocol/pdr-backend/actions/runs/6482493393/job/17602122880

This run took 6 hours and got canceled.

The issue occurs randomly, sometimes the tests work sometimes it gets stuck in an infinite loop.

**Comment by trentmc** [comment]
This is high priority because it adds high friction to actually shipping.

**Comment by trentmc** [comment]
PR #353 is "skip test_trueval_agent.py tests, until #229 fixed"
