### ISSUE TITLE
[Sim, Trader bot] easy sim --> trader bot flow; better backtesting; reconcile Berkay's Oct 2023 PR

### ISSUE THREAD

**Issue by trizin** [oceanprotocol/pdr-backend#231]
### Background / motivation

`pdr_backend` offers three flows for predictoors & traders:
- simulation flow - for rapid iterations to test predictoor approaches and trader approaches
- predictoor bot flow - put a predictoor approach live, make $
- trader bot flow - put a trader approach live, make $

### Pre-requisites

- "[EPIC: YAML] **Add YAML & CLI. 'v0.2' of Predictoor"** [#370](https://github.com/oceanprotocol/pdr-backend/issues/370). 

### DoD 

- [ ] A trader can develop a new trading approach with the "simulation flow" (eg approach3), then easily incorporate it into the "trader bot flow" in just a few lines of code. 
- [ ] Then, make it easy to track performance of live trading, similar to performance of simulated trading 

(Both these can be considered backtesting: the first on simulated data, the second on live data)

### Related:

- In mid Oct, Berkay started taking a swing at this. See this branch: https://github.com/oceanprotocol/pdr-backend/tree/issue231-trader-streamline-strategy-implementation-and-introduce-backtesting
- [pdr-backend#221](https://github.com/oceanprotocol/pdr-backend/issues/232) is like this one, but for predictoors

**Comment by trentmc** [comment]
Trent will take this over the line

**Comment by trentmc** [comment]
This is superseded by [#387](https://github.com/oceanprotocol/pdr-backend/issues/387) "[EPIC] {Mock, real} trades on {historical, live} data, by updating sim_engine & trader". 

Closing.
