### ISSUE TITLE
[Sim, Pdr bot] easy sim --> pdr bot flow; better backtesting

### ISSUE THREAD

**Issue by trizin** [oceanprotocol/pdr-backend#232]
### Background / motivation

`pdr_backend` offers three flows for predictoors & traders:
- simulation flow - for rapid iterations to test predictoor approaches and trader approaches
- predictoor bot flow - put a predictoor approach live, make $
- trader bot flow - put a trader approach live, make $

### Pre-requisites

- "[EPIC: YAML] **Add YAML & CLI. 'v0.2' of Predictoor"** [#370](https://github.com/oceanprotocol/pdr-backend/issues/370). 

### DoD 

- [ ] A predictoor can develop a new prediction approach with the "simulation flow", then easily incorporate it into the "predictoor bot flow" in just a few lines of code. 
- [ ] Then, make it easy to track performance of live predictions, similar to performance of simulated predictions

(Both these can be considered backtesting: the first on simulated data, the second on live data)

**Comment by trentmc** [comment]
This is superseded by [#387](https://github.com/oceanprotocol/pdr-backend/issues/387) "[EPIC] {Mock, real} trades on {historical, live} data, by updating sim_engine & trader"
