### ISSUE TITLE
Add instructions on setting up pm2 config files

### ISSUE THREAD

**Issue by trizin** [oceanprotocol/pdr-backend#260]
**Pre-requisites:**
- [ ] Do [pdr-backend#258](https://github.com/oceanprotocol/pdr-backend/issues/258) first: "Remove onboarding friction: README goes straight to local bot / remote network. **WHY**: issue 257 will make significant changes to the READMEs, hence why we need to do it first. WIP by Trent as of 9am Thu Oct 19.
- [ ] Reconcile [pdr-backend#262](https://github.com/oceanprotocol/pdr-backend/issues/262) with _this_ one. WHY: issue 262 might have overlap. 

**Main work:**
- [ ] Add instructions on setting up pm2 config files into [localbot readme](https://github.com/oceanprotocol/pdr-backend/blob/c2c9e4fd5a8418a250118620413c7e060b49374e/READMEs/localbot-remotenet.md). 
  - NOTE: after doing issue 258, it likely _won't_ be localbot README, but elsewhere. Stay tuned!

**Comment by trentmc** [comment]
Please hold off on doing this until [#258](https://github.com/oceanprotocol/pdr-backend/issues/258) is done. Because that's making big changes to READMEs. I'm working on it now.

**Comment by trentmc** [comment]
This was fixed as part of PR https://github.com/oceanprotocol/pdr-backend/pull/264
