### ISSUE TITLE
[Trader bot] Add approach1 to do simplistic trading

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/pdr-backend#271]
### Status quo

The trader bot is implemented in [predictoor/trader/trader_agent.py](https://github.com/oceanprotocol/pdr-backend/blob/main/pdr_backend/trader/trader_agent.py). 

It has a `do_trade()` function. 
- It inputs two things:
  - the [Feed](https://github.com/oceanprotocol/pdr-backend/blob/main/pdr_backend/models/feed.py) object. Eg Binance ETH/USDT 5min
  - and the prediction: (amount staked up, amt staked down)
- With those inputs, it trades according to its implemented strategy 

Here's what the baseline `do_trade()` currently is:

```python
 async def do_trade(feed: Feed, prediction: Tuple[float, float]):
    """
    @description
        This function is called each time there's a new prediction available.
        By default, it prints the signal.
        The user should implement their trading algorithm here.
    @params
        feed : Feed
            An instance of the Feed object.

        prediction : Tuple[float, float]
            A tuple containing two float values, the unit is ETH:
            - prediction[0]: Amount staked for the price going up.
            - prediction[1]: Total stake amount.
    @note
        The probability of the price going up is determined by dividing
        prediction[0] by prediction[1]. The magnitude of stake amounts indicates
        the confidence of the prediction. Ensure stake amounts
        are sufficiently large to be considered meaningful.
    """
    pred_nom, pred_denom = prediction
    print(f"      {feed} has a new prediction: {pred_nom} / {pred_denom}.")
    # Trade here
    # ...
```

### The problem

Look at the bottom of `do_trade()`. It doesn't actually _do_ any trading yet. Not even the simplest possible trading strategy: "buy if prediction is up; exit 5 min later".

We expect >1 trading strategies over time.

Predictoor bots handle this by having "approach1", "approach2", etc. We could do the same for trader bots.

### DoD

- [x] Implement predictoor/trader/approach1/, where it implements `do_trade()` with the trading strategy: "buy if prediction is up; exit 5 min later". 
- [x] Have good unit tests
- [x] Test that it works for real on mainnet

### Related issues

- [pdr-backend#231](https://github.com/oceanprotocol/pdr-backend/issues/231) used to have "add strategy" plus "do backtesting". But 271 (_this_ issue) does that. So 231 was de-scoped to just "do backtesting"

**Comment by trentmc** [comment]
This exists already. It's the trader bot.

It's in pdr_backend/trader/*

And for the simulations, it already exists too, as part of pdr_backend/predictoor/approach3/.
