### ISSUE TITLE
[Sw eng] Use proper py logging infra, including wrap logs + print into a single fn

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/pdr-backend#285]
### Background / motivation

Problem: Right now some details are being logged, others are being printed, some are both (eg sim_engine.py). This creates duplication and inconsistencies while monitoring.

Potential opportunity: if this was clean, we could log more liberally. It makes it easy to filter out logs of specific modules vs others.

Other motivations:
- helps with analytics. Details in duplicate issue [#476](https://github.com/oceanprotocol/pdr-backend/issues/476)
- will make it possible to properly log when 1 bot has parallel processes or threads. See [comment below](https://github.com/oceanprotocol/pdr-backend/issues/285#issuecomment-1893494196)
- helps with doing ML engineering. Easy to grep/sed logs into floats into convergence plots

### How

Use proper python logging infrastructure like we have in other Ocean components. Eg barge. They have built-in support for log levels from least to most verbose: ERROR -> WARN -> INFO -> DEBUG.

### DoD:
- [ ] All logging is done via a singular function that uses log levels to determine what gets printed/logged

DO NOT OVERENGINEER THIS. It basically amounts to changing print statements to standard py logging statements.

**Comment by trentmc** [comment]
Fyi we have a logging idiom in ocean.py that you could use here.

@calina-c  could fill you in

**Comment by idiom-bytes** [comment]
Good lead/Hot tip.

**Comment by trentmc** [comment]
Another reason for better logging: to help analytics work.

Details: @idiom-bytes has details in a recently-opened issue for logging [#476](https://github.com/oceanprotocol/pdr-backend/issues/476). I closed it as duplicate with _this_ issue.
