### ISSUE TITLE
For backend devs: friction getting local build to pass

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/pdr-backend#293]
# [Motivation]
There are dependencies in the project that are causing CI/CD errors.
When fixing these locally, the libraries don't work because python venv isn't fully configured for development mode.

# Description
github CI/CD is failing on mypy and other dependencies.
(1) as a developer, README should help me get my working environment configured
(2) python env setup could install all dependencies required to test/lint/format repo

### Error 1 - Setting up dev environment
to push a PR into repo, user needs to install `mypy` in venv
```
 pip install mypy
```

### Error 2 - Setting up dev environment
mypy throws errors w/ `requests` and [import-untyped]:
```
pdr_backend/util/subgraph.py:10: error: Library stubs not installed for "requests"  [import-untyped]
pdr_backend/util/test/test_subgraph.py:5: error: Library stubs not installed for "requests"  [import-untyped]
```

to fix this, you need to install `types-requests`
```pip install types-requests```

### DoD

- [ ] Issue is fixed

(obsolete list):
- Developer environment and README.md helps user get all packages and dependencies install
- Developer is able to format/lint/typesafe code to push clean PRs relative to CI/CD requirements

**Comment by trentmc** [comment]
Datapoints:

- `READMEs/backend-dev.md` is the main README for backend devs. Not `README.md`.
- backend-dev.md links to install instructions at `predictoor.md#install-pdr-backend-repo`. Why: minimize friction in predictoor.md flow, and avoid DRY.
- The install instructions include setting up venv, then installing via `pip install -r requirements.txt`. 
- `requirements.txt` gets its list of dependencies from `setup.py`
- For _this_ issue, all that needs to be done is add `mypy `and `types-requests` dependencies to `setup.py`. Don't need to update README.md, backend-dev.md, or other.
