### ISSUE TITLE
[predictoor] Write a script/module to claim ROSE rewards from DFRewards contract

### ISSUE THREAD

**Issue by trizin** [oceanprotocol/pdr-backend#301]
Predictoors need a script or a module in pdr-backend/predictoor to claim their weekly DF ROSE rewards.

**Comment by idiom-bytes** [comment]
Based on https://github.com/oceanprotocol/df-private/issues/68 closing, I'm assuming this is the right ticket.

We had reviewed how this will be implemented, and although we could add support on df-web (and perhaps we should as a backup), most of these users will be running their own bots and will be claiming their PDR rewards as part of their loop.

I support this being implemented there first, and if needed, then implement in df-web.

**Comment by trentmc** [comment]
> Based on https://github.com/oceanprotocol/df-private/issues/68 closing, I'm assuming this is the right ticket.

Correct

**Comment by trentmc** [comment]
> if needed, then implement in df-web

We don't need this. Predictoors run bots in python. They claim their OCEAN sales (& Predictoor DF OCEAN rewards) in python too, via [this script](https://github.com/oceanprotocol/pdr-backend/blob/main/READMEs/payout.md). Therefore it's straightforward for them to claim their ROSE rewards in a script too.
