### ISSUE TITLE
[YAML] [Sw eng] Consolidate logic/interface to serve all <network, contract, addresses>

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/pdr-backend#307]
### Problem
There are currently, different implementations for how to access contracts.
```
pdr_backend/util/subgraph_predictions.py
def get_all_contracts(owner_address: str, network: str) -> List[str]:
    if network != "mainnet" and network != "testnet":
```
Can be consolidated vs. `scripts/addresses.py` and `scripts/get_predictoor_info.py`

[Issue #296](https://github.com/oceanprotocol/pdr-backend/issues/296) also touches on modularizing `scripts/get_predictoor_info.py`, and this might be towards that solution

### DoD
- [ ] Consolidate all deployed/core addresses into a common module/interface
- [ ] All pdr-backend hooks that require contract/addresses should now access through this interface

**Comment by trentmc** [comment]
Where to consolidate to: pdr_backend/util/networkutil.py

_This_ issue is best added as part of issue #296 which already has 6 bullet points of refactors needed to scripts. And then done as part of its PR in #300, so as to avoid overlap.

Roberto: if this is urgent to you, then please work with Mustafa to get #300 over the line.

**Comment by idiom-bytes** [comment]
It is not urgent for me @trentmc

**Comment by trentmc** [comment]
This has been done in the last week as part of work on YAML/CLI branch.
