### ISSUE TITLE
[Predictoor bot approach2] Pdr approach 2 requires model.py/OceanModel

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/pdr-backend#317]
### System Problem:
- Without model.py from `pdr-model-simple`, approach 2 does not run.

### Model Problems:
- The current available trained model inside `pdr-model-simple` does not work
- The current trained gradient boosted models do not work with agent2

### DoD:
- [ ] Implement model.py from pdr-model-simple into approach2, such that you can run a model after having trained it with [pdr-model-simple](https://github.com/oceanprotocol/pdr-model-simple)

**Comment by idiom-bytes** [comment]
Generated HistGradientBoostingClassifier models do not work w/ agent2 as the dataframe/features does not match.
![image](https://github.com/oceanprotocol/pdr-backend/assets/69865342/0d34f647-3667-435f-ad05-80b3b03b4e6b)

**Comment by trentmc** [comment]
We will be deprecating approach2
