### ISSUE TITLE
[Sw eng] Add "github release" to existing release process

### ISSUE THREAD

**Issue by trizin** [oceanprotocol/pdr-backend#382]
### Background / motivation

We already have a release process: https://github.com/oceanprotocol/pdr-backend/blob/main/READMEs/release-process.md

Right now it's bare-bones: 
![Screenshot 2023-11-28 at 09 47 53](https://github.com/oceanprotocol/pdr-backend/assets/5305452/4a376758-db24-4692-9aa6-1b02d2d039c0)

What it's missing: a "github release", like [ocean.py has](https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/release-process.md#step-3-release):
![Screenshot 2023-11-28 at 09 49 20](https://github.com/oceanprotocol/pdr-backend/assets/5305452/e8060120-a383-45a0-99ec-3e73356d68ce)

### TODOs

- [ ] Add a "github release" to pdr-backend's release process, similar to what ocean.py has

**Comment by trentmc** [comment]
Fixed in commit https://github.com/oceanprotocol/pdr-backend/commit/98f17a7803d9d107dc6ef48b2102608da0ba96a2
