### ISSUE TITLE
[YAML, UX] Add migration guidelines

### ISSUE THREAD

**Issue by trizin** [oceanprotocol/pdr-backend#410]
Berkay:

Version v0.2.0 removes the env vars (except PRIVATE_KEY) and main.py files. Instead, agent's are run via pdr CLI and configured via a yaml configuration file.

We must add migration guidelines (v0.1.1 -> v0.2.0) into the releases page to ensure a smooth transition for users upgrading to the latest version pdr-backend.

Trent: it could be the releases page, or elsewhere. We'll explore as we implement this issue

**Comment by trentmc** [comment]
In this commit https://github.com/oceanprotocol/pdr-backend/commit/5362ac2483cf7451a473377f93071a5b8dd083eb, at the very top of the main README, I put a one-liner: 

"⚠️ As of v0.2, the CLI replaces previous `main.py` calls. Update your flows accordingly."

We'll remove it a few weeks after we ship.
