### ISSUE TITLE
[YAML, Sw eng] [Roberto] Review YAML update

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/pdr-backend#411]
### Motivation
- Review YAML + Keep track of changes here + Merge changes into YAML
- Use latest version of Azure VPS to deploy a vanilla barge environment to test against PR

### Problems found, separate issues already created

- [#416](https://github.com/oceanprotocol/pdr-backend/issues/416) No Feeds Found - data_pp.py changes pair standards
- [#417](https://github.com/oceanprotocol/pdr-backend/issues/417) Barge pdr-publisher deploys pair <BTC/TUSD> that should be replaced by <BTC/USDT> pair
- [#418](https://github.com/oceanprotocol/pdr-backend/issues/418) pdr-trader does not work on VPS, throws an exception because it's trying to buy from <BTC/TUSD>
- [#419](https://github.com/oceanprotocol/pdr-backend/issues/419) pdr-trueval does not work on VPS, barge runner does not provide the right args

These are being tracked via the main YAML epic, [#400](https://github.com/oceanprotocol/pdr-backend/issues/400)

### Problems found, separate issues not created yet

- (add to me)

**Comment by idiom-bytes** [comment]
Answer as to why this isn't covered in tests.
1. predictoor agent mocks the feed query and assumes it's correct
```
@enforce_types
def run_agent_test(tmpdir, monkeypatch, predictoor_agent_class):
    monkeypatch.setenv("PRIVATE_KEY", PRIV_KEY)

    ppss = _ppss(tmpdir)

    mock_query = MockQuery(ppss.data_pp)
    monkeypatch.setattr(
        "pdr_backend.ppss.web3_pp.query_feed_contracts",
        mock_query.mock_query_feed_contracts,
    )
```

2. test_web3_pp.py assumes that contract returns `pair: BTC-ETH` but that is not correct
```
FEED_DICT = {  # info inside a predictoor contract
    "name": "Contract Name",
    "address": ADDR,
    "symbol": "test",
    "seconds_per_epoch": 300,
    "seconds_per_subscription": 60,
    "trueval_submit_timeout": 15,
    "owner": "0xowner",
    "pair": "BTC-ETH", # This is not correct
    "timeframe": "1h",
    "source": "binance",
}

**Comment by idiom-bytes** [comment]
On remote azure VM, pdr_trader also fails because it's default runner is configured to buy from `BTC/TUSD` contract, but `pairstr.py::`verify_quote_str` throws a ValueError
![image](https://github.com/oceanprotocol/pdr-backend/assets/69865342/e2ed9b25-6a4d-410f-8e52-230ee461d5cf)

**Comment by idiom-bytes** [comment]
**[4. Issues with pdr-trueval on VPS]**
Seems like pdr-trueval might need to be updated to run w/ latest cli
![image](https://github.com/oceanprotocol/pdr-backend/assets/69865342/5ac9157e-1645-46f9-bdcc-60ce192eb9ac)

**Comment by trentmc** [comment]
Thanks @idiom-bytes ! This is very useful. I will go through and fix these. And make tests to catch them.
