### ISSUE TITLE
[YAML] trueval agent: not filtering out kraken, and says "no pending slots"

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#449]
Parent: [#400](https://github.com/oceanprotocol/pdr-backend/issues/400) "Re-merge YAML & CLI: revive changes, fix bugs, test better, re-merge"

### Issue 1: not filtering out kraken

In YAML branch. On sapphire testnet.

I know it's not filtering out kraken, via code inspection. In `TruevalAgent::get_batch()` it has the following. 
```python
        pending_slots = self.ppss.web3_pp.get_pending_slots(
            timestamp,
        )
```

Note that it only passes in timestamp. No filters. 
- `Web3PP::get_pending_slots()` was built to take in filters, but I removed the args passed in as part of earlier YAML2 work, because the filters were originally from envvars.
- I will need to filter properly. See predictoor_agent.py and trader_agent.py for good patterns: get the unfiltered feeds into the agent, _then_ filter. Why: _much_ easier to debug. I recommend the same thing here (but for slots not feeds).

If I run `pdr trueval ppss.yaml sapphire-testnet` then it gives me

```text
...
Processing slot 1702301100 for Feed: 5m kraken BTC/USDT 
...
```

yet I don't have kraken specified anywhere in my ppss.yaml file.

### Issue 2: It says "no pending slots"

See this log.

```text
(venv) trentmc@tlm-macbook: ~/code/pdr-backend $ pdr trueval ppss.yaml sapphire-testnet
dftool trueval: Begin
Arguments:
PPSS_FILE=ppss.yaml
NETWORK=sapphire-testnet
Subgraph is out of sync, trying again in 5 seconds
Found 0 pending slots, processing 30
No pending slots, sleeping for 30 seconds...
Subgraph is out of sync, trying again in 5 seconds
...
```

I don't know why it gives this behavior. 

- TruevalAgentSingle had given more, as reported in [#444](https://github.com/oceanprotocol/pdr-backend/issues/444)).
- Since the report in # 444, I merged TruevalAgentSingle and TruevalAgentBatch. Now everything is batch. Via this commit https://github.com/oceanprotocol/pdr-backend/commit/0137395427226da48ef2fafb0b7dee11726e2611. Maybe the merge brought errors.

**Comment by calina-c** [comment]
Fixed as part of https://github.com/oceanprotocol/pdr-backend/issues/451
