### ISSUE TITLE
[SW Eng][Agent Logger] Trader Agent and other agent action/event logs

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/pdr-backend#476]
### Motivation
Predictoor agents already log predictions/payouts to report/understand Revenue.
Trader agents will have to log events in order to report/understand PnL. 

To calculate trader-revenue, I'm proposing we provide an interface inside a logger module to log structured events that can streamline any analytical/financial requirements.

![image](https://github.com/oceanprotocol/pdr-backend/assets/69865342/e498a5a9-0223-4538-bcef-06d1831a7e7d)

These events contain all required parameters to understand agent behavior and calculate PNL Logger should update records on top of local `lake/`, and logs should be accessible in `analytics/` through data_factories as a dataframe.

pseudo logger & events
```
logger = logging.getLogger(__name__)

def log_event_start_session(address: str, event_type: str, event_data: dict):
    """
    @description
        Log the start of a session
    """
    event_data = {
        "event_type": event_type,
        "event_data": event_data,
    }
    event_data = json.dumps(event_data)
    event_id = address + event_type + datetime.now()
    logger.log_info(f"event_id: {event_id), event_data: {event_data}")

# event enforces all required data to capture the event and analyze it
def log_event_open_position(address: str, event_type: str, event_data: dict):
    assert event_data.schema == event_open_position_schema
    assert event_data["direction"] in ["long", "short"]

    event_data = json.dumps(event_data)
    event_id = address + event_type + datetime.now()
    logger.log_info(f"event_id: {event_id), event_data: {event_data}")

def log_event_close_position(address: str, event_type: str, event_data: dict):
    assert event_data.schema == event_close_position_schema
    assert event_data["direction"] in ["long", "short"]

    event_data = json.dumps(event_data)
    event_id = address + event_type + datetime.now()
    logger.log_info(f"event_id: {event_id), event_data: {event_data}")
```

**Comment by trentmc** [comment]
This is duplicate with "Use proper py logging infra, including wrap logs + print into a single fn" [#285](https://github.com/oceanprotocol/pdr-backend/issues/285). Closing.

If there are specific extra requirements that you would like in that issue, that were in this issue, please add them there.
