### ISSUE TITLE
Move logic from subgraph_slot.py

### ISSUE THREAD

**Issue by kdetry** [oceanprotocol/pdr-backend#483]
Move logic from subgraph_slot.py - calculate_prediction_result, process_single_slot, aggregate_statistics, calculate_statistics_for_all_assets to accuracy/app.py such that it's separate from subgraph_slots.py code.

DoD:
- [x] move calculate_prediction_result, process_single_slot, aggregate_statistics, calculate_statistics_for_all_assets to `accuracy/app.py`
- [x] move the related test functions to a new test file in the accuracy folder
- [x] make it work

**Comment by idiom-bytes** [comment]
ty @kdetry
