### ISSUE TITLE
[YAML] Add helper functions to manage accounts and predictoors

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/pdr-backend#512]
### Motivation
As part of deploying and managing predictoors, it would improve the UX by having functions that make this easier.

The following cli functions are to be added:
- create_accounts => creates 1->N accounts. prints pk + pub_key
- view_account_balances => shows OCEAN + NATIVE balances for each account submitted
- fund_accounts => distributes n_amount across "addresses,..." in either OCEAN or NATIVE tokens

### DoD
- [ ] cli module, mixins, functions, and utils are created to support 
- [ ] add helper text and descriptions to the cli module
- [ ] tests are written
- [ ] create_accounts is working as expected
- [ ] view_account_balances is working as expected
- [ ] fund_accounts is working as expected

**Comment by trentmc** [comment]
Something to help: the following README has info on how to use python to programmatically create wallets. 
https://github.com/oceanprotocol/pdr-backend/blob/yaml-cli2/READMEs/testnet-faucet.md
