### ISSUE TITLE
[Lake] Improve subgraph and lake error handling such that the lake fills more effectively

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/pdr-backend#514]
### Motivation
There are errors happening when fetching from subgraph/updating the lake, that cause the sync step to fail. Instead, we can improve how we're handling errors, and therefore improve the overall ux.

### DoD
- [x] Rather than throwing an exception on subgraph errors, add a try/catch and let the lake finish updating w/ successfully fetched records
- [x] Rather than throwing an exception on a duplicate, filter all unique records and update the parquet file.
- [x] Add tests that verify handling is working as intended

**Comment by trentmc** [comment]
@idiom-bytes all three tasks are done, should this issue be closed?
