### ISSUE TITLE
[YAML] plots pop up, unwanted, when running test_sim_engine.py

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#525]
### Background / motivation

Commit https://github.com/oceanprotocol/pdr-backend/commit/474ec9c1d697dc8ce7a92be96c15fc1356b5afc3#diff-55bee2d06c47b09f1e5046c2b0efc2c5e1b61536ca765edda5a42a572e490313 turned "do_plot" in test_sim_engine.py to True.

This had two effects:
1. improved code coverage (good)
2. plots popped up when running test (bad: it's annoying behavior)

Ideally we get both (1) and (2).

How: in unit tests, do run through all the plotting code, but don't invoke the "do show" line.

**Comment by calina-c** [comment]
Previously we had tests that had do_plot=False, but that left chunks of code uncovered, and errors might appear in those lines. I will try to disable just plot showing, not plot calcs. Assigning this to myself.

**Comment by idiom-bytes** [comment]
We can probably patch matplotlibs do_plot() internals to do nothing

**Comment by trentmc** [comment]
> Previously we had tests that had do_plot=False, but that left chunks of code uncovered, and errors might appear in those lines. I will try to disable just plot showing, not plot calcs. I'll start working on this.

Exactly. It can probably be just disabling a single "do show" line.

**Comment by trentmc** [comment]
Fixed in PR https://github.com/oceanprotocol/pdr-backend/pull/528, commit https://github.com/oceanprotocol/pdr-backend/commit/413d06587e92d2351d63e8e728dd863910a261f1
