### ISSUE TITLE
[YAML] codeclimate complexity tests are too sensitive, and at least partly redundant

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#526]
From Trent to Calina in slack:

I just went to merge in a med-sized PR ([this](https://github.com/oceanprotocol/pdr-backend/pull/524)). It passed all tests except the new codeclimate check (first time I saw it).

[Here's](https://codeclimate.com/github/oceanprotocol/pdr-backend/pdr_backend/util/signalstr.py/source?from_sha=474ec9c1&to_sha=787a0159) the PR's codeclimate report.

I like that codeclimate has tests on coverage. That's great. That was the main reason for us to add it.

It's also complaining for complexity tests: measures of cognitive complexity, number of arguments to a module, similar blocks of code in tests. This is mostly redundant with mypy (and a bit pylint).

I also tried debugging to fix its complaints, but I didn't find the command-line `complexity` tools that gave the same feedback as the report. (Do they exist? If yes, what is the command?)

TBH I'm thinking we should seriously consider not using codeclimate's complexity tests, given that it's mostly redundant with mypy anyway.

Or, if we do use its complexity tests, we definitely need to tune its testing parameters. (Higher threshold for cognitive complexity, allowed # arguments, etc.) Though in doing that, we're doing work that's redundant with the tuning we did for mypy...  . It's a sign.

I'd prefer that we simply turn off the complexity tests.

----

Let's use _this_ issue for discussion, then resolution.

**Comment by calina-c** [comment]
I’ve unchecked everything except for nested control flow.
