### ISSUE TITLE
[Lake] Add retries around filling the data lake.

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/pdr-backend#563]
### Motivation
As an outcome of reviewing 514/[#552](https://github.com/oceanprotocol/pdr-backend/pull/552), we emphasized that it would be valuable to add a retry around filling the data_lake.

### Outline
Any inputs/triggers that cause gql_lake (and perhaps olhcv_lake too) to fetch/sync, should offer a clean "retry" around the outer-loop such that ["failures from subgraph", "failures from ccxt"] and should provide it in the fn interface.

This should improve the UX of cli_commands/agents, such that building the lake is more resillient to subgraph/api errors.

### DoD:
- [x] Add retries around data_factory loops such that they resume from `last_checkpoint`.
- [x] Continue evolving data factory & data modelling (i.e. beyond pdr analytics) example: volume ticks, f(x) w/ 100 params, improved risk models for trading execution.

**Comment by idiom-bytes** [comment]
@trizin I have discussed with @trentmc when it might be a good time for us to consider a pipeline/workflow tool.

My KISS is:
- Break down every Table/ETL/Step/Object into a single .py file.
- It takes in an input (parquet), and generates (_transform()) an output (table/parquet).

By doing this, everything is self contained, and the pipeline will just step along.

Right now, the steps is just a list of tables that executes in-series.

At some points, we should have dependencies, and retries, and something that looks more like a data-pipeline.

**We're trying not to:** 
- build hadoop/spark/more advanced pipeline

**We're trying to**
- Keep the architecture small and effective
- The smallest scope is a local polars/parquet cron

**Comment by trentmc** [comment]
_Note:_ commit https://github.com/oceanprotocol/pdr-backend/commit/674ca138fdd6afd34905a536498eca26a02246b9 auto-linked above accidentally pointed to this issue, rather than the correct one [#653](https://github.com/oceanprotocol/pdr-backend/issues/563)
