### ISSUE TITLE
[Lake] Build table object and interface to access/update lake data

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/pdr-backend#581]
### Motivation
Rather than accessing/managing tables through files, let's abstract the tables into an object that let's us: load/save/update parquet, manage the schema, etc..

### Outline:
- [x] You shouldn't have to go to GQL DataFactory or ETL to access tables
- [ ] GQL + ETL should be authoritative writing mechanisms, that are updating the lake
- [x] Everything else, should be read-only from tables
- [x] Tables should be wrapped in an Object that helps to built, save, load, tables, etc..
- [x] Tables can help maintain a pointer to dataframe, reduce number of reads, handle caching, etc..

### DoD:
- [ ] Tables offer a clean interface to read/update data
- [ ] Code is updated to use tables through their interfaces

**Comment by KatunaNorbert** [comment]
Shouldn't the ETL do the update and the Tables object just allow you to read the tables?
