### ISSUE TITLE
[Lake] Create + update silver_pdr_predictions table incrementally

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/pdr-backend#610]
### Motivation
We want to build the required data for the first dashboard. To do so, please review the dashboard and the parameters below such that silver_pdr_predictions can provide all data to the plot/dashboard.

https://docs.google.com/presentation/d/18y_nfpc3e-dop5NtfIisgUkc-oPt8dft9WyAnqhSqZg/edit#slide=id.g20f5357f625_0_1639

Create <silver_pdr_predictions> table that: enriches + aggregates pdr-predictions table, such that they satisfy the dashboard requirements:

Enrich the table by creating new columns:
- float reward_df
- float reward_stake
- float slashed
- boolean won
- float sum_staked
- float sum_revenue
- float sum_revenue_stake
- float sum_revenue_df
- float sum_slashed
- others?

### How
Group/Aggregate by [user, contract], such that the results are instantly served to the dashboard.

To calculate n_wins, n_losses, check if the user has predictions skipped, w/o claiming, we'll infer them as being wrong.

**Assumed Loss A: Sparse Claims**
- Claimed 1
- Skipped this claim
- Claimed 2

**Assumed Loss B: Slot Paid Out**
- Join w/ Slot Data
- Check if truevals is true/false
- Check if payout == roundSumStakes/roundSumStakesUp accordingly
- If total paid out == the total from the side staked, then this user has lost

**Assumed Loss C: Please Describe**
- ....

### DoD:
- [x] Verify that aggregate requirements above satisfy dashboard, identify any outstanding ones
- [x] Update bronze table/query as required
- [x] Create silver table/query as required
- [x] Silver table should update incrementally. Meaning that it's using the last `sum_revenue_df` to calculate the next one, and should be able to resume from the `last_datetime` that it ran.
- [x] Silver table should update historically according to [user, contract]. Meaning that a user will claim well-after predicting, and their `sum_` and `count_` columns need to be updated.
- [x] Tests for loading original tables + enriching + aggregating.
- [x] Tests for updating incrementally... basically showing the pipeline being run multiple times, and continuing to calculate/count/sum correctly.
- [ ] Tests for enriching + aggregating should exemplify different data examples (Loss A, B, C) => yielding new rows provided, such that there is some degree of coverage (please see ETL tests and mock data provided).
- [ ] Tests should visibly assert that losses (or other columns/features) are calculated accurately and updated as expected.

**Comment by idiom-bytes** [comment]
Here is an example of what this looks like, when running multiple times and continuing to increment.

```
Table bronze_predictions
======================
Update/Run #1
user_id, contract_id, prediction_index, payout
0xa, 0x1, 0, 1.0
0xa, 0x1, 1, 0.0
0xa, 0x1, 2, 1.0
0xa, 0x1, 3, 3.0

Update/Run #2
user_id, contract_id, prediction_index, payout
0xa, 0x1, 4, 3.0
0xa, 0x1, 5, 5.0


Table silver_predictions
======================
Update/Run #1
user_id, contract_id, prediction_index, payout, sum_payout
0xa, 0x1, 0, 1.0, 1.0
0xa, 0x1, 1, 0.0, 1.0
0xa, 0x1, 2, 1.0, 2.0
0xa, 0x2, 3, 3.0, 5.0

Update/Run #2
user_id, contract_id, prediction_index, payout, sum_payout
0xa, 0x1, 4, 3.0, 8.0
0xa, 0x1, 5, 5.0, 13.0
```
