### ISSUE TITLE
[Lake] ETL has created all gold tables

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/pdr-backend#611]
Add a create_gold_tables step to ETL which is creating the following tables:
- [ ] stake
- [ ] stake-winnings
- [ ] stake-losses
- [ ] non-df-sales-revenue
- [ ] df-sales-revenue
- [ ] net income
- [ ] gross income
- [ ] APR

**Comment by idiom-bytes** [comment]
Hi Norbert, I think there is some confusion here...

I closed this ticket, and updated the **silver_pdr_predictions** ticket
https://github.com/oceanprotocol/pdr-backend/issues/610
