### ISSUE TITLE
[Analytics] Create plot_predictoor_income.py

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/pdr-backend#612]
### Motivation
We want to build the first plot w/ silver_pdr_predictions table.
It will then be implemented in the FE as a separate task.
The goal here is to simply serve the data from the lake, to the dashboard with very few calculations.

![image](https://github.com/oceanprotocol/pdr-backend/assets/69865342/7a96e67a-785c-40c1-a47f-c405dba52c64)

### DoD
- [x] Review [Calina's PR for streamlit](https://github.com/oceanprotocol/pdr-backend/pull/793/files#r1526582129), and replicate the cli + streamlit_entrypoint, such that it's easy for you to get the same streamlit environment going.
- [x] Look at Calina's changes for `SimPlotter.__init__()` such that you understand [how to setup the sim_plotter page](https://github.com/oceanprotocol/pdr-backend/blob/e86f3190597a28e2427d5f17544b83881a504190/pdr_backend/sim/sim_plotter.py), how to setup columns, contianers, and how to initialize plots. **Please [note my comments](https://github.com/oceanprotocol/pdr-backend/pull/793/files#r1526584645).**
- [x] Create your own PredictoorIncomePlotter class, and implement plots that use data from silver_pdr_predictions table to visualize all data.
- [x] create plot_predictoor_income.py and render a simple plot that exemplifies the **Predictoor Income** chart
- [x] create test to show that plot_predictoor_income is created properly
- [x] plot should support multiple user addresses (user_ids), and feeds (contract_ids) **that sum/show the total.**
- [x] tests should cover both single and multiple addresses as a filter
- [x] tests should cover both single and multiple feeds as a filter
- [x] verify that basic plot is rendering as expected, showing: net_income, stake_income, df_income

**Comment by idiom-bytes** [comment]
This was "completed" on the streamlit side with many bugs.

I have tracked this deliverable as outstanding in [#1299](https://github.com/oceanprotocol/pdr-backend/issues/1299) and will be closing this ticket
