### ISSUE TITLE
[Bug] CI fail: Cannot find network "development" in addresses.json

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#622]
Any test using barge fails, e.g.
```text
ERROR pdr_backend/contract/test/test_predictoor_contract.py::test_get_trueValSubmitTimeout - ValueError: Cannot find network "development" in addresses.json
ERROR pdr_backend/contract/test/test_predictoor_contract.py::test_submit_prediction_trueval_payout - ValueError: Cannot find network "development" in addresses.json
ERROR pdr_backend/contract/test/test_predictoor_contract.py::test_redeem_unused_slot_revenue - ValueError: Cannot find network "development" in addresses.json
============ 10 failed, 431 passed, 22 errors in 171.06s (0:02:51) =============
```

I get this every 10 or 20 runs in CI. I can immediately fix it by simply re-running CI.

[Here's](https://github.com/oceanprotocol/pdr-backend/actions/runs/7916484756/job/21610426945) an example log, for a run where all I did was change a single README.

It's probably because the tests start to run, yet barge isn't ready yet. 

Is there a way to make this more reliable, without too much implementation effort, and without massively slowing down CI runtime?

Most promising idea: use tricks now in Ocean Node, where it waits long enough (but no longer)

Other ideas: have a pre-existing running Barge, or image with ganache state pre-set

**Comment by alexcos20** [comment]
most likely was fixed in latest barge.

**Comment by trentmc** [comment]
> most likely was fixed in latest barge.

Good to know. I'll assume so. I haven't seen problems in the last few days. If an problem emerges we can re-open this or create a new github issue.
