### ISSUE TITLE
[Lake][ETL] Insert GQL data into PersistentStore

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/pdr-backend#682]
### Motivation
Update gql_data_factory to integrate [PersistentStore](https://github.com/oceanprotocol/pdr-backend/pull/652) and push data to raw tables.

**Persist SLA** Only new records should be fetched & inserted into db.
1. get last timestamp from db.table
2. fetch subgraph from_last_timestamp to_now
3. insert subgraph new_records into db.table
![image](https://github.com/oceanprotocol/pdr-backend/assets/69865342/df92b37e-8bd9-4e1b-9402-5b125552953c)

DoD:
- [x] tables in duckdb are created w/ the same schema that we persist in files
- [x] update table schemas & system to use pydantic if required, rather than creating multiple schemas or mappings
- [x] gql_data_factory fetch/update functions insert new records into db raw tables
- [x] tests validate db has new records registered
- [x] etl.py is ready to be updated, as all raw subgraph records are being correctly inserted into the db

**Comment by kdetry** [comment]
Although Pydantic is a great tool, it's not always necessary since we already have Polars data schemas that validate the data structure. Using Pydantic now would result in double validation.

**Comment by idiom-bytes** [comment]
The whole etl pipeline is now implemented using CSV + DuckDB.

It has been verified and merged into PR #685, which is a large Epic that includes many other updates to improve Lake/ETL/etc...
https://github.com/oceanprotocol/pdr-backend/issues/685
