### ISSUE TITLE
[Analytics] Create plot_predictoor_income.py #612

### ISSUE THREAD

**Issue by JamesKano0128** [oceanprotocol/pdr-backend#687]
Motivation
We want to build the first plot w/ silver_pdr_predictions table.
It will then be implemented in the FE as a separate task.
The goal here is to simply serve the data from the lake, to the dashboard with very few calculations.

image

DoD
 create plot_predictoor_income.py and render a simple plot that exemplifies the Predictoor Income chart
 create test to show that plot_predictoor_income is created properly
 plot should support multiple user addresses (user_ids), and feeds (contract_ids) that sum/show the total.
 tests should cover both single and multiple addresses as a filter
 tests should cover both single and multiple feeds as a filter
 verify that basic plot is rendering as expected, showing: net_income, stake_income, df_income

**Comment by kindlyman343423** [comment]
This issue resolved.
