### ISSUE TITLE
[Bug][Pdr bot] Submit prediction fails with insufficient balance to pay the fees, despite wallets having enough balance

### ISSUE THREAD

**Issue by trizin** [oceanprotocol/pdr-backend#735]
Submit prediction fails with insufficient balance to pay the fees, despite wallets having enough balance.

This problem occurred on a MacOS running a fresh pdr-backend instance, specifically on commit 50399e8f08b42c401e65dc8ff7458f0adda48248.

Attempts to replicate this error on a Linux setup with the same pdr-backend version were unsuccessful, as predictions were submitted without any issues. This suggests that the problem might be specific to MacOS or potentially linked to the sapphire.py, although tests for sapphire.py on MacOS have been passing.

The issue appears to be isolated to the prediction submission functionality. Further investigation is required to pinpoint the exact cause and replicate the issue for a resolution.

**Comment by trentmc** [comment]
Low priority because: only seen once, haven't been able to reproduce
