### ISSUE TITLE
[DX] VisualStudio linter complains about README formatting

### ISSUE THREAD

**Issue by Pfed-prog** [oceanprotocol/pdr-backend#743]
**Describe the bug**

I have forked the repo and my readme plug in is very angry.

**To Reproduce**

Install https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint
<img width="969" alt="image" src="https://github.com/oceanprotocol/pdr-backend/assets/66903336/89794ee4-6388-4c83-a073-022903ab009c">

**Screenshots**
<img width="1280" alt="image" src="https://github.com/oceanprotocol/pdr-backend/assets/66903336/ff66d1c8-d5a6-4fd2-8c8b-9ea4e9deaad7">

Any chance I can pr the readme improvements?

**Comment by trentmc** [comment]
I've renamed this issue to be more specific
