### ISSUE TITLE
[Sim] Sim engine plots obstruct the rest of the screen

### ISSUE THREAD

**Issue by Pfed-prog** [oceanprotocol/pdr-backend#744]
I am very excited about the predictoor and I have cloned the repo. 

I have run the default script but the plot obstructs everything else on the computer. Any chance the plot could be more manageable.
It aslo disappears after the script stops. I have no idea where to find it.

**Comment by trentmc** [comment]
We recently created [#749)(https://github.com/oceanprotocol/pdr-backend/issues/749) "[Sim] Output sim_engine plots -> streamlit -> webapp" which should help a lot. It will likely be a week or two before done.

> It aslo disappears after the script stops. I have no idea where to find it.

This was the original design intent. However I agree, it's annoying. The issue above will address this too. In the meantime, just put a `import pdb; pdb.set_trace()` at the tail end of SimEngine.run(), ie [here](https://github.com/oceanprotocol/pdr-backend/blob/4fe5944027ffde2333ee7eddf17ef52b79b95994/pdr_backend/sim/sim_engine.py#L113).

**Comment by trentmc** [comment]
I've renamed the issue to be more specific, and linked to it from # 749.

**Comment by idiom-bytes** [comment]
@Pfed-prog we have now pushed an update to main that lets you run the streamlit app. This is a bigger effort to build an interface that is easier to build and use.

Please download the main branch, and read the update to the readme so you know how to run the app along with the sim engine.

Please give that a try and then let us know how it went so we can close this issue.

**Comment by Pfed-prog** [comment]
> @Pfed-prog we have now pushed an update to main that lets you run the streamlit app. This is a bigger effort to build an interface that is easier to build and use.
> 
> Please download the main branch, and read the update to the readme so you know how to run the app along with the sim engine.
> 
> Please give that a try and then let us know how it went so we can close this issue.

Thank you so much for pinging me, I have updated local repo and run the code

The graphs do not prevent me from using my computer, thank you very much. 

<img width="939" alt="image" src="https://github.com/oceanprotocol/pdr-backend/assets/66903336/23368a19-fca5-4726-83ec-efc33c1ad857">
