### ISSUE TITLE
[Lake][SWE] Improve CSVDataStore and PersistentDataStore instantiation inside Table.

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/pdr-backend#773]
### Motivation
Tables object (many) is instantiating (1) CSVDataStore and (2) PersistentDataStore with each table.
This is unnecessary, and could perhaps lead to other issues such as w/ duckdb connections and other unknowns.

(1) CSVDataStore and (2) PersistentDataStore should likely be used as singletons, or perhaps there is a better way to implement this.

### DoD:
- [ ] Consider a cleaner way to implement CSVDataStore + PersistentDataStore
- [ ] Table has been cleaned up to address CSVDataStore + PersistentDataStore
- [ ] All code that uses CSVDataStore + PersistentDataStore has been addressed

**Comment by kdetry** [comment]
It is recommended to use the "multiton" pattern instead of singletona for classes with argument(s) in their constructors.
I am going to implement it

**Comment by idiom-bytes** [comment]
Closing. This issue has been completed.

Changes are available inside of DuckDB integration PR until it's merged into main.
