### ISSUE TITLE
[Lake][ETL] DuckDB Integration - Cleanup any refs to `select * from tables`

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/pdr-backend#809]
### Background

As a result of DuckDB integration, there is some remaining code that may `select * from table` as a way to "get a lazy pointer".

### DoD
- [x] Clean up any final queries that fetch the whole database system. No `select * from table_name` anywhere.

**Comment by kdetry** [comment]
To remove entire tables through queries, we need to refactor/re-develop the Predfilter class.
