### ISSUE TITLE
[Bug][Pdr bot] Network name mismatch in Predictoor.md and Addresses.json

### ISSUE THREAD

**Issue by graceful-coder** [oceanprotocol/pdr-backend#827]
**Description**
When following the Predictoor.md README steps, the `pdr predictoor 2 my_ppss.yaml sapphire-testnet` command fails with the error: `ValueError: Cannot find network "sapphire-testnet" in addresses.json`. See screenshot.
<img width="1081" alt="value-error-addresses" src="https://github.com/oceanprotocol/pdr-backend/assets/101472818/d32bf626-89c3-483b-a774-0fe8a927028c">

Running the command with the Oasis testnet spelled the same way as in the addresses.json file, `pdr predictoor 2 my_ppss.yaml oasis_saphire_testnet` fails with the error: `AssertionError: PublisherSS needs a 'oasis_saphire_testnet' key`. See screenshot. 
<img width="934" alt="assertion-error-publisherss" src="https://github.com/oceanprotocol/pdr-backend/assets/101472818/789be367-cc7b-4f5d-84b9-e46d39c2f4cf">

**To Reproduce**
1. Follow the Predictoor.md steps up to the command `pdr predictoor 2 my_ppss.yaml sapphire-testnet`
2. Wait until the payout scripts finish running, then the Value Error will appear
3. Rerun the command with the testnet name as defined in Addresses.json `pdr predictoor 2 my_ppss.yaml oasis_saphire_testnet`, then the Assertion Error will appear

**Expected behavior**
Submitting predictions successfully on Oasis Sapphire Testnet.

**Comment by calina-c** [comment]
Can not reproduce this on current `main` branch.
