### ISSUE TITLE
ETL + DuckDB encountered issues

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/pdr-backend#859]
While testing the ETL + DuckDB integration from this branch I run into the following issues:

- [ ] The ETL fetched all the predictions until today and then started fetching all predictions again from the start. Check image:<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1kxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--63abda8dcde668fc6b02d67f9ef9c6fe713cc359/Screenshot%202024-04-04%20at%2013.18.07.png" alt="Screenshot 2024-04-04 at 13.18.07.png" />
- [x] Looks like the 'now' value of the fin_timestr of lake_ss can't be interpreted and breaks the flow:<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEExQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bf02952ff18fbcc6bf6c459ba80013c1617a19b3/Screenshot%202024-04-04%20at%2014.53.06.png" alt="Screenshot 2024-04-04 at 14.53.06.png" />
- [x] If the fetched data length is 0 the table is not created and the ETL flow crashes. Run into this with the subscriptions table:<img width="1086" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFExQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9913dc0cd97291034ab0ab3cd8bd525ed45c95f4/Screenshot%202024-04-04%20at%2017.49.14.png" alt="Screenshot 2024-04-04 at 17.49.14.png" />

-------
- [ ]  The logic to retrieve the last timestamp from the CSV data store is not working correctly. It has to be fixed

**Comment by idiom-bytes** [comment]
st: 1st of March
fin: now

it was a clean lake so no lake_data folder

**Comment by kdetry** [comment]
The logic to retrieve the last timestamp from the CSV data store is not working correctly.
