### ISSUE TITLE
[Proposal] Remove matplotlib

### ISSUE THREAD

**Issue by calina-c** [oceanprotocol/pdr-backend#869]
I think we are slowly moving away from matplotlib and working towards plotly.
- sim engine doesn't use matplotlib anymore
- this PR (https://github.com/oceanprotocol/pdr-backend/pull/829) is in progress, and it plots user revenues with plotly

The only *real* usages of matplotlib remain in:
- plot_slot_daily_statistics
- plot_traction_daily_statistics
- plot_traction_cum_sum_statistics

And some references in setup.py, mypy.ini and test patches:
![screenshot_2024-04-09_at_10 38 08_720](https://github.com/oceanprotocol/pdr-backend/assets/4101015/4737c00a-9e62-410b-a609-a8633b6fd020)

(screenshotted from the branch in #829).

I propose we remove matplotlib altogether, after #829 is merged. If agreed, I will not approve any more dependabot updates and I'll scoop up the remnants in a new branch (or on top of #829).

_Originally posted by @calina-c in https://github.com/oceanprotocol/pdr-backend/issues/865#issuecomment-2044372435_

**Comment by calina-c** [comment]
Attn: @trentmc @KatunaNorbert @idiom-bytes

**Comment by trentmc** [comment]
Calina & I discussed this. I'm ok with removing matplotlib. However I do need a way to do rapid-turnaround flows in AI model development. See [#871](https://github.com/oceanprotocol/pdr-backend/issues/871). We agreed to use plotly for that. (Fingers crossed that plotly is useful enough then; if not then I'll be sure to speak up:)
