### ISSUE TITLE
[SimEngine] Precision, recall and f1 not updating

### ISSUE THREAD

**Issue by calina-c** [oceanprotocol/pdr-backend#880]
Sim Engine has precision, recall and f1 all zero, in certain runs. It seems to usually happen at the start of the run. I've checked the logs and the values reported are zero, so it doesn't seem to be a plotting issue. It seems to be lower-level, so assigning this to Trent.

Leaving #856 open to check after this is done.

**Comment by trentmc** [comment]
@calina-c can you try to reproduce the error? If you can't, I guess we close this issue for now.

**Comment by calina-c** [comment]
I can't reproduce it now, but I could reproduce it when I opened the issue. As could Roberto and yourself. It might be that the code has updated in the meantime, or an issue with the data at that particular point giving bizarre results.

I will close both this and the plot issue for now and we'll stumble into this again if not fixed.
