### ISSUE TITLE
[ETL][Lake] Fetching data stuck in loop

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/pdr-backend#904]
I run into this issue mainly on the Predictions and Payouts data fetching, and when it happens, after fetching the latest data it keeps on fetching from the beginning again and creates a loop. It is usually fixed when I stop the process and run it again. I suspect that something is off with handling the last date offset.

**Comment by idiom-bytes** [comment]
Please describe the exact steps to reproduce the problem and provide snapshots of the output so we can look into the logic of the loop ending + restarting.
