### ISSUE TITLE
ppss.yaml conflict with multisim sweeping

### ISSUE THREAD

**Issue by calina-c** [oceanprotocol/pdr-backend#916]
Running commands using the ppss.yaml file in the tree should work out of the box.
Right now, multisim does not properly work, due to constraints with aimodel input feeds being swept, but not predictoor feeds. #912 will fix parts of this, but in the meantime we should fix the default sweeping to enable multisim on the "virgin" ppss.yaml

**Comment by trentmc** [comment]
Fixed in PR #920, commit https://github.com/oceanprotocol/pdr-backend/commit/d1c2435a0fb1de061efa68a0622f27da85753b3a
