### ISSUE TITLE
[CLI, Bug] 'pdr fund_accounts" requires you to pass-in command-name twice

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/pdr-backend#928]
**Describe the bug**
The CLI `fund_accounts` command requires you to call the cli command name twice.

**To Reproduce**
Call the cli command `fund_accounts`
```
python pdr fund_accounts 1 0xaddress ppss.yaml sapphire-mainnet
```

This will throw an error... You have to instead use.
```
python pdr fund_accounts fund_accounts 1 0xaddress ppss.yaml sapphire-mainnet
```

**Expected behavior**
You should be able to simply use the command like any other cli command, and not have to pass in the command twice.
```
python pdr fund_accounts 1 0xaddress ppss.yaml sapphire-mainnet
```

### DoD
- [x] User can use fund_accounts cli command as expected

**Comment by calina-c** [comment]
@trentmc I removed an extra line which added the command name. The `add_arguments_bulk` function already adds it, so it was doubly added. Indeed it worked if adding the export line, but all the other commands worked with `python` as well as with plain `pdr`.
