### ISSUE TITLE
[Bug, sim plots] Inconsistent plot-stretching <> unstretching when browser widens <> narrows

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#969]
**Describe the bug**

I'm running the new Dash-based sim plots.

If I widen the browser (eg Chrome), the plots stretch wider. OK, cool. Image 1 below.

Then if I narrow the browser, plots don't go narrow as I would have expected. Rather, the plots stay as wide as they'd stretched to, and a horizontal scroll bar appear, I have to scroll among the plots. Image 2 below.

What I expect: when I re-narrow a browser, plots should go narrow (vs staying wide).

## Image 1: browser is wide
![Screenshot 2024-04-30 at 14 27 07](https://github.com/oceanprotocol/pdr-backend/assets/5305452/c3539330-c756-4b5c-bd16-c742cd1f3838)

## Image 2: browser is narrow (after being wide)

Note the scroll bar at the bottom.

![Screenshot 2024-04-30 at 14 27 19](https://github.com/oceanprotocol/pdr-backend/assets/5305452/6dd0d949-e8ab-44a5-a26a-f76bff214a82)

**Comment by calina-c** [comment]
@KatunaNorbert I think this is one for you
