### ISSUE TITLE
[Lake][Bug] The bronze PDR slots table has more than it needs to include

### ISSUE THREAD

**Issue by kdetry** [oceanprotocol/pdr-backend#975]
The bronze PDR slots table has more than it needs to include. Reported by @KatunaNorbert on slack

The timestamp value is also weird, some of them are just "1"

**DoD**

- [ ] Inspect and fix the SQL
- [ ] Test manually sure about the data result

**Comment by idiom-bytes** [comment]
@kdetry please fill this bug w/ proper information...

**Comment by idiom-bytes** [comment]
As far as I can tell, the `bronze_pdr_slot` table is not working at the moment.

It is currently disabled in a couple of PRs, and will likely remain so as we prepare to get duckdb-integration PR release candidate ready.
