### ISSUE TITLE
[CLI] 'pdr view accounts' is too verbose

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#977]
### Status quo

```text
> pdr view_accounts 0xef7802fe057209F67A519eA639158CF017D5faD4 my_ppss.yaml sapphire-mainnet
2024-05-01 06:27:24,535 cli INFO pdr view_accounts: Begin
2024-05-01 06:27:24,536 cli INFO Arguments:
2024-05-01 06:27:24,536 cli INFO ACCOUNTS=['0xef7802fe057209F67A519eA639158CF017D5faD4']
2024-05-01 06:27:24,536 cli INFO PPSS_FILE=my_ppss.yaml
2024-05-01 06:27:24,536 cli INFO NETWORK=sapphire-mainnet
2024-05-01 06:27:24,536 cli INFO Nested args: {}
2024-05-01 06:27:24,969 web3_accounts INFO Account 0xef7802fe057209F67A519eA639158CF017D5faD4
2024-05-01 06:27:24,970 web3_accounts INFO Native token balance: 1928.599344571 eth
2024-05-01 06:27:24,970 web3_accounts INFO OCEAN balance: 3728.898761752895 eth
```

This is too long for a simple 

### What we want

```text
> pdr view_accounts 0xef7802fe057209F67A519eA639158CF017D5faD4 my_ppss.yaml sapphire-mainnet
1928.599344571 ROSE, 3728.898761752895 OCEAN
```

And, don't support >1 address. If people want a balance for another address, just call the command again.

### TODOs / DoD

- [ ] Implement "what we want"

**Comment by idiom-bytes** [comment]
I understand that now w/ the manager this has changed significantly... however, as we work towards more UI-integration by leveraging the CLI strongly-validated interface.

This is still a good feature to have such that it can be exposed there and it adds no complexity or verbosity to the CLI function/interface.

**Comment by trentmc** [comment]
> I would expect address-list support working wherever possible.
> It adds no complexity or verbosity to the CLI function/interface 

Incorrect, for _this_ CLI command. For others where the command does more stuff that isn't just a compact one-line output it might make more sense. I will now elaborate...

If >1 addresses are supported here, then each output line would also need to have the address string. That's a lot of extra characters for someone's brain to have to process.

Let's say you wanted to see balances for two accounts. Here's how it currently does it, with this ticket now done:
```text
> pdr print_balances 0xef7802fe057209F67A519eA639158CF017D5faD4 my_ppss.yaml sapphire-mainnet
1928.599344571 ROSE, 3728.898761752895 OCEAN

> pdr print_balances 0x95222290dd7278aa3ddd389cc1e1d165cc4bafe5 my_ppss.yaml sapphire-mainnet
122.766431861 ROSE, 0.13370118061932 OCEAN
```

Note how each call has a super-specific input and output. Compact. Composable. Very unix-y. 

Whereas with I address-list support, it is:
```text
> pdr print_balances 0xef7802fe057209F67A519eA639158CF017D5faD4,0x95222290dd7278aa3ddd389cc1e1d165cc4bafe5 my_ppss.yaml sapphire-mainnet
1928.599344571 ROSE, 3728.898761752895 OCEAN for address 0xef7802fe057209F67A519eA639158CF017D5faD4
122.766431861 ROSE, 0.13370118061932 OCEAN for address 0x95222290dd7278aa3ddd389cc1e1d165cc4bafe5
```

Now, this call has become bloated, with a less specific input and output. Not compact. Ignores the possibility of composability. Not very unix-y. 

To conclude: support for >1 address adds more complexity, moving the UX away from a clean unix-y approach. 

This github issue has been completed with the unix-y approach. Let's keep it that way.
