### ISSUE TITLE
Issue with Logging Small Stake Amounts Due to Formatting

### ISSUE THREAD

**Issue by trizin** [oceanprotocol/pdr-backend#990]
When formatting stake amounts using ":.2f", values less than 0.01 are not displayed. This behavior mirrors the issue addressed in [#952](https://github.com/oceanprotocol/pdr-backend/issues/952). Implement a solution that ensures these small stake amounts are also logged appropriately.

Lines: https://github.com/oceanprotocol/pdr-backend/blob/main/pdr_backend/predictoor/predictoor_agent.py#L153-L154

**Comment by calina-c** [comment]
@trizin can I take this? I think I can implement something similar to the fix I did in #952. And I would like to keep it consistent with the idea of customisable logging.
